version: 2
jobs:
  build:
    working_directory: ~/memux
    docker:
      - image: node:8
        environment:
          NODE_ENV: test
      - image: zookeeper:latest
      - image: ches/kafka:latest
        environment:
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - node_modules-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: yarn run coverage

      - store_artifacts:
          path: coverage
